-- MySQL Script generated by MySQL Workbench
-- Mon Dec  1 20:42:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ticketbooth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ticketbooth` ;

-- -----------------------------------------------------
-- Schema ticketbooth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketbooth` ;
-- -----------------------------------------------------
-- Schema ticket_booth
-- -----------------------------------------------------
USE `ticketbooth` ;

-- -----------------------------------------------------
-- Table `ticketbooth`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`user` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`ticket_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`ticket_type` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`ticket_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `based_on` SET("payment", "time_purchase", "validity", "special", "discount") NULL,
  `contant_name` VARCHAR(45) NULL,
  `contact_email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`event` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `title` VARCHAR(200) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`event_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`event_date` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`event_date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_venue` VARCHAR(45) NULL,
  `tota_tickets` INT NULL,
  `event_id` INT NOT NULL,
  `seating_mode` ENUM('GA', 'SEATED') NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_date_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_date_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `ticketbooth`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`venue` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`venue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `slug` VARCHAR(45) NULL,
  `capacity` INT NULL,
  `venue_type` VARCHAR(45) NULL,
  `accessible_weelchair` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`seat` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section` VARCHAR(45) NOT NULL,
  `row` VARCHAR(3) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `is_accessible` TINYINT NULL,
  `venue_id` INT NOT NULL,
  `status` ENUM("AVAILABLE", "HOLD", "SOLD") NOT NULL DEFAULT 'AVAILABLE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_seat_venue1_idx` (`venue_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_venue1`
    FOREIGN KEY (`venue_id`)
    REFERENCES `ticketbooth`.`venue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`event_date_has_seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`event_date_has_seat` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`event_date_has_seat` (
  `event_date_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `price` DECIMAL(19,5) NULL,
  `ticket_type_id` INT NOT NULL,
  PRIMARY KEY (`event_date_id`, `seat_id`),
  INDEX `fk_event_date_has_seat_seat1_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_event_date_has_seat_event_date1_idx` (`event_date_id` ASC) VISIBLE,
  INDEX `fk_event_date_has_seat_ticket_type1_idx` (`ticket_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_date_has_seat_event_date1`
    FOREIGN KEY (`event_date_id`)
    REFERENCES `ticketbooth`.`event_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_date_has_seat_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `ticketbooth`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_date_has_seat_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `ticketbooth`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`ticket` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `ticket_type_id` INT NOT NULL,
  `to_name` VARCHAR(255) NULL,
  `event_date_id` INT NOT NULL,
  `seat_id` INT,
PRIMARY KEY (`id`),
UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
INDEX `fk_ticket_ticket_type1_idx` (`ticket_type_id` ASC) VISIBLE,
INDEX `fk_ticket_event_date1_idx` (`event_date_id` ASC) VISIBLE,

-- This unique index enforces one ticket per (event_date, seat)
UNIQUE INDEX `uniq_ticket_eventdate_seat` (`event_date_id`, `seat_id`) VISIBLE,

CONSTRAINT `fk_ticket_ticket_type1`
  FOREIGN KEY (`ticket_type_id`)
  REFERENCES `ticketbooth`.`ticket_type` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,

CONSTRAINT `fk_ticket_event_date1`
  FOREIGN KEY (`event_date_id`)
  REFERENCES `ticketbooth`.`event_date` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,

CONSTRAINT `fk_ticket_event_date_has_seat1`
  FOREIGN KEY (`event_date_id`, `seat_id`)
  REFERENCES `ticketbooth`.`event_date_has_seat` (`event_date_id`, `seat_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`venue_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`venue_types` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`venue_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `size` SET('small', 'medium', 'large', 'multitud') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `seated_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`venue_has_venue_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`venue_has_venue_types` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`venue_has_venue_types` (
  `venue_id` INT NOT NULL,
  `venue_types_id` INT NOT NULL,
  PRIMARY KEY (`venue_id`, `venue_types_id`),
  INDEX `fk_venue_has_venue_types_venue_types1_idx` (`venue_types_id` ASC) VISIBLE,
  INDEX `fk_venue_has_venue_types_venue_idx` (`venue_id` ASC) VISIBLE,
  CONSTRAINT `fk_venue_has_venue_types_venue`
    FOREIGN KEY (`venue_id`)
    REFERENCES `ticketbooth`.`venue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venue_has_venue_types_venue_types1`
    FOREIGN KEY (`venue_types_id`)
    REFERENCES `ticketbooth`.`venue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`event_date_has_ticket_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`event_date_has_ticket_type` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`event_date_has_ticket_type` (
  `event_date_id` INT NOT NULL,
  `ticket_type_id` INT NOT NULL,
  `max_quantity` INT NULL,
  `remaining_tickets` INT NULL,
  `price` DECIMAL(19) NULL,
  `number_people_included` INT NULL DEFAULT 1,
  `expiration_date` DATETIME NULL,
  PRIMARY KEY (`event_date_id`, `ticket_type_id`),
  INDEX `fk_event_date_has_ticket_type_ticket_type1_idx` (`ticket_type_id` ASC) VISIBLE,
  INDEX `fk_event_date_has_ticket_type_event_date1_idx` (`event_date_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_date_has_ticket_type_event_date1`
    FOREIGN KEY (`event_date_id`)
    REFERENCES `ticketbooth`.`event_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_date_has_ticket_type_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `ticketbooth`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`event_has_venue_has_venue_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`event_has_venue_has_venue_types` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`event_has_venue_has_venue_types` (
  `event_id` INT NOT NULL,
  `venue_has_venue_types_venue_id` INT NOT NULL,
  `venue_has_venue_types_venue_types_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `venue_has_venue_types_venue_id`, `venue_has_venue_types_venue_types_id`),
  INDEX `fk_event_has_venue_has_venue_types_venue_has_venue_types1_idx` (`venue_has_venue_types_venue_id` ASC, `venue_has_venue_types_venue_types_id` ASC) VISIBLE,
  INDEX `fk_event_has_venue_has_venue_types_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_has_venue_has_venue_types_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `ticketbooth`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_venue_has_venue_types_venue_has_venue_types1`
    FOREIGN KEY (`venue_has_venue_types_venue_id` , `venue_has_venue_types_venue_types_id`)
    REFERENCES `ticketbooth`.`venue_has_venue_types` (`venue_id` , `venue_types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`order` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `total_tickets` INT NULL,
  `amount` VARCHAR(45) NULL,
  `payment_source` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Order_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticketbooth`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`order_hast_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`order_hast_tickets` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`order_hast_tickets` (
  `order_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `ticket_id`),
  INDEX `fk_Order_has_ticket_ticket1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_Order_has_ticket_Order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_ticket_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ticketbooth`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_ticket_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `ticketbooth`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`role` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`role_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`role_has_user` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`role_has_user` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `fk_role_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_role_has_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ticketbooth`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticketbooth`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`permission` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketbooth`.`role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketbooth`.`role_has_permission` ;

CREATE TABLE IF NOT EXISTS `ticketbooth`.`role_has_permission` (
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_id` ASC) VISIBLE,
  INDEX `fk_role_has_permission_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ticketbooth`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `ticketbooth`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Stored Procedure `sp_reserve_ga_tickets`
-- Provides transactional reservation semantics for GA inventory
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS `ticketbooth`.`sp_reserve_ga_tickets`;
DELIMITER $$
CREATE PROCEDURE `ticketbooth`.`sp_reserve_ga_tickets`(
  IN p_event_date_id INT,
  IN p_ticket_type_id INT,
  IN p_quantity INT
)
proc_body:BEGIN
  DECLARE rows_changed INT DEFAULT 0;

  IF p_quantity <= 0 THEN
    SELECT 0 AS reserved_rows;
    LEAVE proc_body;
  END IF;

  START TRANSACTION;

  UPDATE event_date_has_ticket_type
  SET remaining_tickets = remaining_tickets - p_quantity
  WHERE event_date_id = p_event_date_id
    AND ticket_type_id = p_ticket_type_id
    AND remaining_tickets >= p_quantity;

  SET rows_changed = ROW_COUNT();

  IF rows_changed = 0 THEN
    ROLLBACK;
  ELSE
    COMMIT;
  END IF;

  SELECT rows_changed AS reserved_rows;
END$$
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
